### ISSUE TITLE
`从私有仓库拉取镜像`章节变量名错误

### ISSUE THREAD

**Issue by mrgaolei** [k8smeetup/k8smeetup.github.io#4]
https://k8smeetup.github.io/docs/tasks/configure-pod-container/pull-image-private-registry/

```shell
kubectl create secret docker-registry regsecret --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>
```

这里创建的名字为`regsecret`

```yaml

apiVersion: v1 
kind: Pod 
metadata:   
    name: private-reg 
    spec:   
        containers:   
            - name: private-reg-container
        image: <your-private-image>
    imagePullSecrets:   
        - name: regcred
--
```

这里用到的name为`regcred`

这个是无法工作的
